name: JavaScript CI
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  js-lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          working-directory: client
      - run: 'pnpm i && pnpm check && pnpm lint'